# Use a lightweight Python image
FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Download the model files explicitly
# RUN python -c "\
# from transformers import Blip2ForConditionalGeneration, AutoProcessor;\
# model = Blip2ForConditionalGeneration.from_pretrained('manan145/blip2_lora_vqa_model', force_download=True);\
# processor = AutoProcessor.from_pretrained('manan145/blip2_lora_vqa_model', force_download=True);"

# Copy the backend source code
COPY . .

# Expose the FastAPI port
EXPOSE 8080

# Command to start FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]