version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  # Map backend port
    container_name: backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"  # Map frontend port
    container_name: frontend
    depends_on:
      - backend  # Ensure backend starts before frontend
